#!/bin/env ruby

require_relative 'lib'

$dict = parse_dict 'dict/18766-2009.txt'

def translate_line(line)
  fail unless line.length % 3 == 0
  line.scan(/[A-Z]{3}/).map do |x|
    mapped = $dict[x]
    if mapped == nil
      '?'
    else
      mapped
    end
  end.join('')
end

telegrams = Telegram.parse(File.read('samples/18766-navtex.txt'))
telegrams.each do |t|
  puts t.header
  puts translate_line telegrams[0].body.join('').gsub(/\n+/, '')
  puts TELEGRAM_END
  puts
end
